package signals

import "math"

// DigitStats tracks the distribution of the last decimal digit of a symbol's
// quote over a rolling window of ticks.
//
// IMPORTANT HONESTY NOTE: Deriv's Volatility Indices are generated by an
// internal random number model (Deriv states this openly). The last digit
// of each tick is effectively an independent random draw. That means this
// tracker is a DESCRIPTIVE tool - it shows you what the recent distribution
// looks like - not a predictive one. Any digit will naturally drift above or
// below 10% just from ordinary randomness, and that drift has no bearing on
// the next digit. Use backtest.Run to check whether a specific rule built on
// top of this actually beats chance before trusting it with money.
type DigitStats struct {
	window   []int // ring buffer of last digits seen
	capacity int
	pos      int
	filled   int
	counts   [10]int
}

// NewDigitStats creates a tracker with the given rolling window size.
func NewDigitStats(windowSize int) *DigitStats {
	return &DigitStats{
		window:   make([]int, windowSize),
		capacity: windowSize,
	}
}

// LastDigit extracts the last decimal digit of a quote given the symbol's
// pip_size (number of decimal places Deriv quotes it to).
func LastDigit(quote float64, pipSize int) int {
	scaled := math.Round(quote * math.Pow10(pipSize))
	d := int(math.Mod(scaled, 10))
	if d < 0 {
		d += 10
	}
	return d
}

// Push adds a new digit observation, evicting the oldest if the window is full.
func (d *DigitStats) Push(digit int) {
	if digit < 0 || digit > 9 {
		return
	}
	if d.filled == d.capacity {
		old := d.window[d.pos]
		d.counts[old]--
	} else {
		d.filled++
	}
	d.window[d.pos] = digit
	d.counts[digit]++
	d.pos = (d.pos + 1) % d.capacity
}

// Ready reports whether the window has enough samples to be meaningful.
func (d *DigitStats) Ready() bool {
	return d.filled >= d.capacity/2
}

// Frequencies returns the current percentage (0-100) each digit represents
// of the window, e.g. Frequencies()[7] = 12.5 means digit 7 made up 12.5% of
// recent ticks.
func (d *DigitStats) Frequencies() [10]float64 {
	var freq [10]float64
	if d.filled == 0 {
		return freq
	}
	for i, c := range d.counts {
		freq[i] = float64(c) / float64(d.filled) * 100
	}
	return freq
}

// EvenOddSplit returns the percentage of the window that landed on an even
// digit vs odd digit.
func (d *DigitStats) EvenOddSplit() (evenPct, oddPct float64) {
	if d.filled == 0 {
		return 0, 0
	}
	var even, odd int
	for digit, c := range d.counts {
		if digit%2 == 0 {
			even += c
		} else {
			odd += c
		}
	}
	return float64(even) / float64(d.filled) * 100, float64(odd) / float64(d.filled) * 100
}

// OverUnderSplit returns the percentage of the window at or below `barrier`
// (Under) vs strictly above it (Over) - matching Deriv's DIGITOVER/DIGITUNDER
// barrier semantics.
func (d *DigitStats) OverUnderSplit(barrier int) (overPct, underPct float64) {
	if d.filled == 0 {
		return 0, 0
	}
	var over, under int
	for digit, c := range d.counts {
		if digit > barrier {
			over += c
		} else {
			under += c
		}
	}
	return float64(over) / float64(d.filled) * 100, float64(under) / float64(d.filled) * 100
}

// WindowSize returns the configured capacity.
func (d *DigitStats) WindowSize() int { return d.capacity }
